import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { auth } from "../config/firebase";
import { RecaptchaVerifier, signInWithPhoneNumber } from "firebase/auth";

export default function Home() {
	const [number, setNumber] = useState("");
	const [otp, setOtp] = useState("");
	const router = useRouter();

	const generateRecaptcha = () => {
		window.recaptchaVerifier = new RecaptchaVerifier(
			"sign-in-button",
			{
				size: "invisible",
				callback: (response) => {
					// reCAPTCHA solved, allow signInWithPhoneNumber.
				},
			},
			auth
		);
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		generateRecaptcha();
		const appVerifier = window.recaptchaVerifier;
		signInWithPhoneNumber(auth, number, appVerifier)
			.then((confirmationResult) => {
				// SMS sent. Prompt user to type the code from the message, then sign the
				// user in with confirmationResult.confirm(code).
				window.confirmationResult = confirmationResult;
				// ...
			})
			.catch((error) => {
				// Error; SMS not sent
				console.log(error);
			});
	};

	const verifyOTP = (e) => {
		const confirmationResult = window.confirmationResult;
		confirmationResult
			.confirm(otp)
			.then((result) => {
				// User signed in successfully.
				const user = result.user;
				// console.log(user)
				router.push("/welcome");

				// ...
			})
			.catch((error) => {
				// User couldn't sign in (bad verification code?)
				// ...
			});
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles["form-container"]}>
				<h1>OPT test</h1>
				<form onSubmit={handleSubmit}>
					<div className={styles.flex}>
						<label htmlFor="ph">Enter your phone number</label>
						<input
							type="text"
							name="ph"
							value={number}
							onChange={(e) => setNumber(e.target.value)}
						/>
						<button id="sign-in-button" className={styles["btn-opt"]} type="submit">
							Get OTP
						</button>
					</div>
					<div className={styles.flex}>
						<label htmlFor="otp">Enter the OPT code</label>
						<input
							type="text"
							name="otp"
							value={otp}
							onChange={(e) => setOtp(e.target.value)}
						/>
						<button className={styles["btn-submit"]} onClick={verifyOTP}>
							Submit
						</button>
					</div>
				</form>
			</div>
		</div>
	);
}
